# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f94f9e1191a93d022672b8d6685231bc2d602bdab09453fa149ab013b29c6f8c4e7126680e23600ab0b4179fe04f257061fe060e7e1725b34339f8394192f5a9

test:
  secret_key_base: 4f6c34c804de81b0534576fe46efc89c6dfc74d8f420a360b1c4ad3b27ef6fec400e5a3eadb5dc23da1b2a04d635a379d700e4ab4de1a7fc852bd3b93177cddf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
